# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoMLBE4bdYbwRpZ6jS5u7rNY1YbCl8B_
"""

StudentInfo=[]
n=int(input("Enter Number of students: "))
for i in range(n):
  name = input("Enter Name: ")
  subject = input("Enter Subject: ")
  score = input("Enter score: ")
  d = {name:{subject:score}}
  StudentInfo.append(d)
print(StudentInfo)
with open('my_file.txt', 'w') as f:
    for line in StudentInfo:
        f.write(f"{line}\n")

